# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow lets you generate SLSA provenance file for your project.
# The generation satisfies level 3 for the provenance requirements - see https://slsa.dev/spec/v0.1/requirements
# The project is an initiative of the OpenSSF (openssf.org) and is developed at
# https://github.com/slsa-framework/slsa-github-generator.
# The provenance file can be verified using https://github.com/slsa-framework/slsa-verifier.
# For more information about SLSA and how it improves the supply-chain, visit slsa.dev.

name: SLSA generic generator
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      digests: ${{ steps.hash.outputs.hashes }}
      file: ${{ steps.hash.outputs.content }}

    steps:
      - uses: actions/checkout@v3

      # ========================================================
      #
      # Step 1: Build your artifacts.
      #
      # ========================================================
      - name: Build artifacts
        run: |
            echo "# These are some amazing artifacts."
            echo "artifact1" > artifact1
            echo "artifact2" > artifact2
            cat artifact1
      # ========================================================
      #
      # Step 2: Add a step to generate the provenance subjects
      #         as shown below. Update the sha256 sum arguments
      #         to include all binaries that you generate
      #         provenance for.
      #
      # ========================================================
      # - name: Generate subject for provenance
      #   id: hash
      #   run: |
          # set -euo pipefail
          # List the artifacts the provenance will refer to.
          # files=$(ls *)
          # Generate the subjects (base64 encoded)
          # ls *
          # echo "digest :######################## hashes=$(sha256sum $files | base64 -w0)" 
          # echo "content=$(cat app.js)" >> "${GITHUB_OUTPUT}"
          # echo "hashes=$(sha256sum $files | base64 -w0)" >> "${GITHUB_OUTPUT}"
          
  provenance:
    needs: [build]
    permissions:
      actions: read   # To read the workflow path.
      id-token: write # To sign the provenance.
      contents: write # To add assets to a release.
      packages: write
    uses: laurentsimon/byob-doc/.github/workflows/builder_example_slsa3.yml@v0.0.1
    with:
      artifact: "app.js"
      content: "testing"
      rekor-log-public: false
